### ISSUE TITLE
申请权限后界面无反应

### ISSUE THREAD

**Issue by DragonsQC** [yewei02538/HiPermission#1]
申请权限成功后，app的界面就定住了，需要按一下返回键，app的界面才能操作

**Comment by yewei02538** [comment]
具体的操作流程是什么样的呢？

**Comment by DragonsQC** [comment]
HiPermission的弹框消失后，onGuarantee回调之后，app怎么点都没有反应，需要按一下返回键，app才可以操作

**Comment by yewei02538** [comment]
已解决，改下版本号即可，sorry

**Comment by DragonsQC** [comment]
nice!
