### ISSUE TITLE
onGuarantee 是什么时候调用？

### ISSUE THREAD

**Issue by yanyusong** [yewei02538/HiPermission#5]
能不能详细描述一下几个回调函数的使用场景和区别？谢谢

**Comment by yewei02538** [comment]
你好，申请多个权限4个方法都会回调，全部权限申请成功会回调`onFinish()`,取消申请会回调`onClose()`,只会调用1次。拒绝会调用`onDeny()`,同意权限`onGuarantee()`会调用多次
申请单个权限只会调用`onDeny()`和`onGuarantee()`
